[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[project]
name = "frender"
version = "1.0.0"
description = "A CLI tool for rendering jinja2 templates"
authors = [{ name = "Andrew Arasmith", email = "andrew@arasmith.org" }]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "AGPL-3.0-or-later" }

dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
    "dotenv>=0.9.9",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
]

[project.scripts]
frender = "frender:main"
